In [1]:
#14 july 2023

import numpy as np

arr1 = np.array([1,2,3])

print(arr1)





[1 2 3]


In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
print(arr1.shape)


(3,)


In [4]:
print(arr1[2])

3


In [5]:
arr1[2]=5
arr1

array([1, 2, 5])

In [6]:
arr2=np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
arr2[1][2]

5

In [8]:
print(arr2.shape)


(2, 3)


In [9]:
arr[1,2]

NameError: name 'arr' is not defined

In [10]:
arr2[1,2]

5

In [11]:
arr2[1,-1]

5

In [12]:
arr2[1,-2]

4

In [13]:
arrS = np.array(['china','India','USA', 'morroco'])
arrS

array(['china', 'India', 'USA', 'morroco'], dtype='<U7')

In [14]:
arrR = np.arange(0,20,2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arrL = np.linspace(0,10, 20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
arr= np.random.rand(10)


In [17]:
arr= np.random.rand(10)
arr


array([0.45349577, 0.25571303, 0.54280733, 0.96493802, 0.12399999,
       0.61944732, 0.41783786, 0.35550824, 0.13042989, 0.3465584 ])

In [18]:
arr = np.random.rand(3,4)
arr


array([[0.67975228, 0.77630664, 0.43269655, 0.16749175],
       [0.36870772, 0.71969178, 0.8917926 , 0.56250609],
       [0.2715943 , 0.56329204, 0.85968918, 0.10501766]])

In [19]:
print(np.zeroes(10))
print('/n')
print(np.zeroes((2,3)))


AttributeError: module 'numpy' has no attribute 'zeroes'

In [20]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(np.ones((3,4)))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [25]:
arr= [0, 1, 2]
print(np.repeat(arr , 3))

[0 0 0 1 1 1 2 2 2]


In [26]:
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [27]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [30]:
arr = np.random.rand(5,5)
arr


array([[0.74154107, 0.67477998, 0.78857178, 0.19185236, 0.35149008],
       [0.7547273 , 0.38944562, 0.38601123, 0.59220407, 0.53875774],
       [0.91345111, 0.63611349, 0.80579891, 0.25529706, 0.54010963],
       [0.31882072, 0.40899744, 0.26132854, 0.39078399, 0.39757923],
       [0.76871643, 0.67770975, 0.64163922, 0.66659623, 0.99164796]])

In [31]:
np.diag(arr)


array([0.74154107, 0.38944562, 0.80579891, 0.39078399, 0.99164796])

In [32]:
arr.ndim

2

In [33]:
arr.size

25

In [34]:
arr.shape

(5, 5)

In [35]:
np.random.randint(-10,10,4)


array([-7,  7, -7,  0])

In [36]:
arr+10


array([[10.74154107, 10.67477998, 10.78857178, 10.19185236, 10.35149008],
       [10.7547273 , 10.38944562, 10.38601123, 10.59220407, 10.53875774],
       [10.91345111, 10.63611349, 10.80579891, 10.25529706, 10.54010963],
       [10.31882072, 10.40899744, 10.26132854, 10.39078399, 10.39757923],
       [10.76871643, 10.67770975, 10.64163922, 10.66659623, 10.99164796]])

In [37]:
arr+20


array([[20.74154107, 20.67477998, 20.78857178, 20.19185236, 20.35149008],
       [20.7547273 , 20.38944562, 20.38601123, 20.59220407, 20.53875774],
       [20.91345111, 20.63611349, 20.80579891, 20.25529706, 20.54010963],
       [20.31882072, 20.40899744, 20.26132854, 20.39078399, 20.39757923],
       [20.76871643, 20.67770975, 20.64163922, 20.66659623, 20.99164796]])

In [38]:
arr-10

array([[-9.25845893, -9.32522002, -9.21142822, -9.80814764, -9.64850992],
       [-9.2452727 , -9.61055438, -9.61398877, -9.40779593, -9.46124226],
       [-9.08654889, -9.36388651, -9.19420109, -9.74470294, -9.45989037],
       [-9.68117928, -9.59100256, -9.73867146, -9.60921601, -9.60242077],
       [-9.23128357, -9.32229025, -9.35836078, -9.33340377, -9.00835204]])

In [39]:
arr/2

array([[0.37077054, 0.33738999, 0.39428589, 0.09592618, 0.17574504],
       [0.37736365, 0.19472281, 0.19300561, 0.29610204, 0.26937887],
       [0.45672555, 0.31805675, 0.40289946, 0.12764853, 0.27005482],
       [0.15941036, 0.20449872, 0.13066427, 0.19539199, 0.19878961],
       [0.38435821, 0.33885487, 0.32081961, 0.33329811, 0.49582398]])

In [40]:
np.exp(arr)

array([[2.09916799, 1.9636009 , 2.20025175, 1.21149164, 1.42118365],
       [2.12703141, 1.47616222, 1.47110119, 1.80796892, 1.71387646],
       [2.49291101, 1.8891245 , 2.23848414, 1.29084503, 1.71619501],
       [1.37550471, 1.50530786, 1.29865425, 1.47813918, 1.48821769],
       [2.15699581, 1.96936223, 1.89959217, 1.94759684, 2.69567318]])

In [41]:
arr

array([[0.74154107, 0.67477998, 0.78857178, 0.19185236, 0.35149008],
       [0.7547273 , 0.38944562, 0.38601123, 0.59220407, 0.53875774],
       [0.91345111, 0.63611349, 0.80579891, 0.25529706, 0.54010963],
       [0.31882072, 0.40899744, 0.26132854, 0.39078399, 0.39757923],
       [0.76871643, 0.67770975, 0.64163922, 0.66659623, 0.99164796]])

In [44]:
np.log10(arr)

array([[-0.12986479, -0.17083781, -0.10315877, -0.71703285, -0.45408693],
       [-0.12220994, -0.40955317, -0.41340006, -0.22752861, -0.26860648],
       [-0.03931469, -0.19646539, -0.09377332, -0.59295418, -0.26751808],
       [-0.49645346, -0.38827942, -0.58281316, -0.40806324, -0.40057632],
       [-0.11423384, -0.16895627, -0.1927091 , -0.17613715, -0.00364248]])

In [45]:
np.tan(arr)

array([[0.91591943, 0.80006403, 1.00636747, 0.1942414 , 0.36671804],
       [0.94046558, 0.41040702, 0.40639979, 0.67275254, 0.59774226],
       [1.29557208, 0.73852025, 1.04165712, 0.26099205, 0.59957866],
       [0.33008113, 0.43343977, 0.2674446 , 0.41197166, 0.41994263],
       [0.96718096, 0.80488045, 0.74709485, 0.78672884, 1.52916438]])

In [46]:
arr


array([[0.74154107, 0.67477998, 0.78857178, 0.19185236, 0.35149008],
       [0.7547273 , 0.38944562, 0.38601123, 0.59220407, 0.53875774],
       [0.91345111, 0.63611349, 0.80579891, 0.25529706, 0.54010963],
       [0.31882072, 0.40899744, 0.26132854, 0.39078399, 0.39757923],
       [0.76871643, 0.67770975, 0.64163922, 0.66659623, 0.99164796]])

In [48]:
np.sum(arr, axis=0)

array([3.49725663, 2.78704629, 2.88334968, 2.09673371, 2.81958464])

In [49]:
np.min(arr, axis=0)

array([0.31882072, 0.38944562, 0.26132854, 0.19185236, 0.35149008])

In [50]:
np.mean(arr, axis=0)

array([0.69945133, 0.55740926, 0.57666994, 0.41934674, 0.56391693])

In [51]:
np.std(arr, axis=0)

array([0.20015004, 0.13013862, 0.21790568, 0.18465849, 0.22669231])

In [52]:
np.var(arr, axis=0)

array([0.04006004, 0.01693606, 0.04748289, 0.03409876, 0.0513894 ])

In [53]:
arr[1:,2:4] 


array([[0.38601123, 0.59220407],
       [0.80579891, 0.25529706],
       [0.26132854, 0.39078399],
       [0.64163922, 0.66659623]])

In [54]:
arr

array([[0.74154107, 0.67477998, 0.78857178, 0.19185236, 0.35149008],
       [0.7547273 , 0.38944562, 0.38601123, 0.59220407, 0.53875774],
       [0.91345111, 0.63611349, 0.80579891, 0.25529706, 0.54010963],
       [0.31882072, 0.40899744, 0.26132854, 0.39078399, 0.39757923],
       [0.76871643, 0.67770975, 0.64163922, 0.66659623, 0.99164796]])

In [55]:
np.sort(arr, axis=1)

array([[0.19185236, 0.35149008, 0.67477998, 0.74154107, 0.78857178],
       [0.38601123, 0.38944562, 0.53875774, 0.59220407, 0.7547273 ],
       [0.25529706, 0.54010963, 0.63611349, 0.80579891, 0.91345111],
       [0.26132854, 0.31882072, 0.39078399, 0.39757923, 0.40899744],
       [0.64163922, 0.66659623, 0.67770975, 0.76871643, 0.99164796]])

In [56]:
np.sort(arr)

array([[0.19185236, 0.35149008, 0.67477998, 0.74154107, 0.78857178],
       [0.38601123, 0.38944562, 0.53875774, 0.59220407, 0.7547273 ],
       [0.25529706, 0.54010963, 0.63611349, 0.80579891, 0.91345111],
       [0.26132854, 0.31882072, 0.39078399, 0.39757923, 0.40899744],
       [0.64163922, 0.66659623, 0.67770975, 0.76871643, 0.99164796]])

In [57]:
arr.T
# T stands for transpose//
# rows are now columns here //

array([[0.74154107, 0.7547273 , 0.91345111, 0.31882072, 0.76871643],
       [0.67477998, 0.38944562, 0.63611349, 0.40899744, 0.67770975],
       [0.78857178, 0.38601123, 0.80579891, 0.26132854, 0.64163922],
       [0.19185236, 0.59220407, 0.25529706, 0.39078399, 0.66659623],
       [0.35149008, 0.53875774, 0.54010963, 0.39757923, 0.99164796]])

In [3]:
arr[:3,:].T

NameError: name 'arr' is not defined

In [4]:
arr = np.random.rand(5,5)
arr

NameError: name 'np' is not defined

In [6]:
# 15 july 2023 //

import numpy as np

arr= np.random.rand(5,5)

In [7]:
arr

array([[0.77415523, 0.07368743, 0.62150997, 0.01990177, 0.76813989],
       [0.05523089, 0.74737942, 0.96032446, 0.27097639, 0.95039496],
       [0.81342675, 0.28672982, 0.33515166, 0.69699835, 0.52604946],
       [0.70870721, 0.38051723, 0.3205428 , 0.699648  , 0.59440287],
       [0.44399703, 0.15363579, 0.31898533, 0.81206101, 0.6590895 ]])

In [8]:
arr[:3,:]

array([[0.77415523, 0.07368743, 0.62150997, 0.01990177, 0.76813989],
       [0.05523089, 0.74737942, 0.96032446, 0.27097639, 0.95039496],
       [0.81342675, 0.28672982, 0.33515166, 0.69699835, 0.52604946]])

In [9]:
arr[:3,:].T
arr[:3,:].transpose() 
# this is the original version.

# here rows are now columns
# we have use first three rows and columns

array([[0.77415523, 0.05523089, 0.81342675],
       [0.07368743, 0.74737942, 0.28672982],
       [0.62150997, 0.96032446, 0.33515166],
       [0.01990177, 0.27097639, 0.69699835],
       [0.76813989, 0.95039496, 0.52604946]])

In [10]:
arr[:3,:].flatten()

# it has converted it again in it's original form mentioned above //

array([0.77415523, 0.07368743, 0.62150997, 0.01990177, 0.76813989,
       0.05523089, 0.74737942, 0.96032446, 0.27097639, 0.95039496,
       0.81342675, 0.28672982, 0.33515166, 0.69699835, 0.52604946])

In [12]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [13]:
arr1 = np.append(arr,8)
arr1

array([4, 5, 6, 7, 8, 8])

In [14]:
arr2 = np.insert(arr, 0, [1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
arr3 = np.delete(arr2, [1,3])
arr3

array([1, 3, 5, 6, 7, 8])

In [32]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr_cat = np.concatenate((arr1,arr2), axis=1)
print(arr_cat)

# this will show me an error when axis is 0 and arr1 has 3 values each

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [33]:
catV = np.vstack((arr1, arr2))
catV
# vertical stack

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [35]:
cat = np.hstack((arr1, arr2))
cat
# horizontal

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [36]:
# unique values
arr = np.array([1,2,3,2,4,1,4,5,2,6])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [38]:
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 3 1 2 1 1]


In [40]:
# intersection, differentiation, neither

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1, arr2))
print(np.union1d(arr1, arr2))

# what's in array 1 but not in array 2 : use diff
print(np.setdiff1d(arr1, arr2))

# what's in 2 but not in 1 and vice-versa
print(np.setxor1d(arr1, arr2))

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]


In [ ]:
# important points to remember while working on R : 

# imagine you have some NA values in your column and you dont want to include them you can simply remove them by using (THIS IS FOR MEAN)
# mean(tablename$columnname, na.rm = TRUE)    ->>>> syntax